/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;

import javax.swing.ImageIcon;

/**
 *
 * @author luiis
 */
public class admUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admUsuarios.class.getName());

    /**
     * Creates new form agregarUsuario
     */
    public admUsuarios() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBase = new javax.swing.JPanel();
        administrarUsuariosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        usuarioBuscado = new javax.swing.JTextField();
        nuevoCajeroButton = new javax.swing.JButton();
        eliminarCajeroButton = new javax.swing.JButton();
        panelNuevoCajero = new javax.swing.JPanel();
        nuevoCajeroLabel = new javax.swing.JLabel();
        nuevoUserLabel = new javax.swing.JLabel();
        nombreCompletoLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        nuevoUsuarioUser = new javax.swing.JTextField();
        nuevoUsuarioNombre = new javax.swing.JTextField();
        nuevoUsuarioPass = new javax.swing.JPasswordField();
        permisosTabbed = new javax.swing.JTabbedPane();
        permisosVentas = new javax.swing.JPanel();
        permVentasProductosComunes = new javax.swing.JCheckBox();
        permAplicarDescuentos = new javax.swing.JCheckBox();
        permRevisarHistorialV = new javax.swing.JCheckBox();
        permCobrarUnTicket = new javax.swing.JCheckBox();
        permEliminarArtVenta = new javax.swing.JCheckBox();
        permUsarBuscadorP = new javax.swing.JCheckBox();
        permUsarVarios = new javax.swing.JCheckBox();
        permFiarProductos = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        permisosClientes = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        permisosProductos = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        permisosInventario = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        permisosOtros = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        buscarCajeroButton = new javax.swing.JButton();
        panelEliminarCajero = new javax.swing.JPanel();
        eliminarCajero = new javax.swing.JButton();
        eliminarCajeroLabel = new javax.swing.JLabel();
        seleccionarCajeroLabel = new javax.swing.JLabel();
        cajeroComboBoxElim = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgBase.setBackground(new java.awt.Color(255, 255, 255));

        administrarUsuariosLabel.setBackground(new java.awt.Color(0, 205, 203));
        administrarUsuariosLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        administrarUsuariosLabel.setForeground(new java.awt.Color(255, 255, 255));
        administrarUsuariosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administrarUsuariosLabel.setText("Administrar Usuarios");
        administrarUsuariosLabel.setOpaque(true);

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usuariosTable);

        usuarioBuscado.setBackground(new java.awt.Color(255, 255, 255));
        usuarioBuscado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        nuevoCajeroButton.setBackground(new java.awt.Color(65, 220, 127));
        nuevoCajeroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nuevoCajeroButton.setForeground(new java.awt.Color(255, 255, 255));
        nuevoCajeroButton.setText("Nuevo Cajero");
        nuevoCajeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCajeroButtonActionPerformed(evt);
            }
        });

        eliminarCajeroButton.setBackground(new java.awt.Color(65, 220, 127));
        eliminarCajeroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarCajeroButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarCajeroButton.setText("Eliminar Cajero");
        eliminarCajeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCajeroButtonActionPerformed(evt);
            }
        });

        panelNuevoCajero.setBackground(new java.awt.Color(255, 255, 255));
        panelNuevoCajero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelNuevoCajero.setVisible(false);

        nuevoCajeroLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nuevoCajeroLabel.setForeground(new java.awt.Color(102, 102, 102));
        nuevoCajeroLabel.setText("NUEVO CAJERO");
        panelNuevoCajero.add(nuevoCajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nuevoUserLabel.setForeground(new java.awt.Color(0, 0, 0));
        nuevoUserLabel.setText("Nombre de usuario:");
        panelNuevoCajero.add(nuevoUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        nombreCompletoLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreCompletoLabel.setText("Nombre completo:");
        panelNuevoCajero.add(nombreCompletoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setText("Contraseña:");
        panelNuevoCajero.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 136, 80, 20));
        panelNuevoCajero.add(nuevoUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 56, 210, 30));
        panelNuevoCajero.add(nuevoUsuarioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, 30));
        panelNuevoCajero.add(nuevoUsuarioPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 210, 30));

        permisosVentas.setBackground(new java.awt.Color(255, 255, 255));

        permVentasProductosComunes.setForeground(new java.awt.Color(0, 0, 0));
        permVentasProductosComunes.setText("Utilizar Productos Comunes");

        permAplicarDescuentos.setForeground(new java.awt.Color(0, 0, 0));
        permAplicarDescuentos.setText("Aplicar Descuentos");

        permRevisarHistorialV.setForeground(new java.awt.Color(0, 0, 0));
        permRevisarHistorialV.setText("Revisar Historial de Ventas");

        permCobrarUnTicket.setForeground(new java.awt.Color(0, 0, 0));
        permCobrarUnTicket.setText("Cobrar un Ticket");

        permEliminarArtVenta.setForeground(new java.awt.Color(0, 0, 0));
        permEliminarArtVenta.setText("Eliminar Articulos de Venta");

        permUsarBuscadorP.setForeground(new java.awt.Color(0, 0, 0));
        permUsarBuscadorP.setText("Usar Buscador de Productos");

        permUsarVarios.setForeground(new java.awt.Color(0, 0, 0));
        permUsarVarios.setText("Usar Varios");

        permFiarProductos.setForeground(new java.awt.Color(0, 0, 0));
        permFiarProductos.setText("Avalar Productos");

        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Manejar Varios Tickets");

        javax.swing.GroupLayout permisosVentasLayout = new javax.swing.GroupLayout(permisosVentas);
        permisosVentas.setLayout(permisosVentasLayout);
        permisosVentasLayout.setHorizontalGroup(
            permisosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permisosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permisosVentasLayout.createSequentialGroup()
                        .addGroup(permisosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(permAplicarDescuentos)
                            .addComponent(permRevisarHistorialV)
                            .addComponent(permCobrarUnTicket)
                            .addComponent(permEliminarArtVenta)
                            .addComponent(permUsarBuscadorP)
                            .addComponent(permUsarVarios)
                            .addComponent(permFiarProductos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(permisosVentasLayout.createSequentialGroup()
                        .addComponent(permVentasProductosComunes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(19, 19, 19))))
        );
        permisosVentasLayout.setVerticalGroup(
            permisosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permisosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permVentasProductosComunes)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permAplicarDescuentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permRevisarHistorialV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permCobrarUnTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permEliminarArtVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permUsarBuscadorP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permUsarVarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permFiarProductos)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        permisosTabbed.addTab("Ventas", permisosVentas);

        permisosClientes.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("Adm. Clientes Avalados");

        javax.swing.GroupLayout permisosClientesLayout = new javax.swing.GroupLayout(permisosClientes);
        permisosClientes.setLayout(permisosClientesLayout);
        permisosClientesLayout.setHorizontalGroup(
            permisosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox2)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        permisosClientesLayout.setVerticalGroup(
            permisosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox2)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        permisosTabbed.addTab("Clientes", permisosClientes);

        permisosProductos.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setText("Añadir Productos");

        jCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setText("Eliminar Productos");

        jCheckBox5.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setText("Editar Productos");

        javax.swing.GroupLayout permisosProductosLayout = new javax.swing.GroupLayout(permisosProductos);
        permisosProductos.setLayout(permisosProductosLayout);
        permisosProductosLayout.setHorizontalGroup(
            permisosProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permisosProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        permisosProductosLayout.setVerticalGroup(
            permisosProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        permisosTabbed.addTab("Productos", permisosProductos);

        permisosInventario.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox6.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setText("Ver Inventario");

        javax.swing.GroupLayout permisosInventarioLayout = new javax.swing.GroupLayout(permisosInventario);
        permisosInventario.setLayout(permisosInventarioLayout);
        permisosInventarioLayout.setHorizontalGroup(
            permisosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox6)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        permisosInventarioLayout.setVerticalGroup(
            permisosInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox6)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        permisosTabbed.addTab("Inventario", permisosInventario);

        permisosOtros.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox7.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setText("Permisos de Administrador");

        javax.swing.GroupLayout permisosOtrosLayout = new javax.swing.GroupLayout(permisosOtros);
        permisosOtros.setLayout(permisosOtrosLayout);
        permisosOtrosLayout.setHorizontalGroup(
            permisosOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox7)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        permisosOtrosLayout.setVerticalGroup(
            permisosOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permisosOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox7)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        permisosTabbed.addTab("Otros", permisosOtros);

        panelNuevoCajero.add(permisosTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, 290));

        buscarCajeroButton.setBackground(new java.awt.Color(65, 220, 127));
        buscarCajeroButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarCajeroButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceLupaWhite.png")));

        panelEliminarCajero.setBackground(new java.awt.Color(255, 255, 255));
        panelEliminarCajero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelEliminarCajero.setVisible(false);

        eliminarCajero.setText("Eliminar");
        panelEliminarCajero.add(eliminarCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        eliminarCajeroLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eliminarCajeroLabel.setForeground(new java.awt.Color(102, 102, 102));
        eliminarCajeroLabel.setText("ELIMINAR CAJERO");
        panelEliminarCajero.add(eliminarCajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        seleccionarCajeroLabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCajeroLabel.setText("Seleccionar Cajero:");
        panelEliminarCajero.add(seleccionarCajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        panelEliminarCajero.add(cajeroComboBoxElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 30));

        javax.swing.GroupLayout bgBaseLayout = new javax.swing.GroupLayout(bgBase);
        bgBase.setLayout(bgBaseLayout);
        bgBaseLayout.setHorizontalGroup(
            bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBaseLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgBaseLayout.createSequentialGroup()
                        .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelNuevoCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bgBaseLayout.createSequentialGroup()
                                .addComponent(buscarCajeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nuevoCajeroButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarCajeroButton)
                                .addGap(64, 64, 64))))
                    .addComponent(administrarUsuariosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBaseLayout.createSequentialGroup()
                    .addContainerGap(299, Short.MAX_VALUE)
                    .addComponent(panelEliminarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        bgBaseLayout.setVerticalGroup(
            bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(administrarUsuariosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoCajeroButton)
                    .addComponent(eliminarCajeroButton)
                    .addComponent(buscarCajeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNuevoCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(31, 31, 31))
            .addGroup(bgBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBaseLayout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(panelEliminarCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoCajeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCajeroButtonActionPerformed
        panelEliminarCajero.setVisible(false);
        panelNuevoCajero.setVisible(true);

    }//GEN-LAST:event_nuevoCajeroButtonActionPerformed

    private void eliminarCajeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCajeroButtonActionPerformed
        panelNuevoCajero.setVisible(false);
        panelEliminarCajero.setVisible(true);
    }//GEN-LAST:event_eliminarCajeroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new admUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrarUsuariosLabel;
    private javax.swing.JPanel bgBase;
    private javax.swing.JButton buscarCajeroButton;
    private javax.swing.JComboBox<String> cajeroComboBoxElim;
    private javax.swing.JButton eliminarCajero;
    private javax.swing.JButton eliminarCajeroButton;
    private javax.swing.JLabel eliminarCajeroLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreCompletoLabel;
    private javax.swing.JButton nuevoCajeroButton;
    private javax.swing.JLabel nuevoCajeroLabel;
    private javax.swing.JLabel nuevoUserLabel;
    private javax.swing.JTextField nuevoUsuarioNombre;
    private javax.swing.JPasswordField nuevoUsuarioPass;
    private javax.swing.JTextField nuevoUsuarioUser;
    private javax.swing.JPanel panelEliminarCajero;
    private javax.swing.JPanel panelNuevoCajero;
    private javax.swing.JLabel passLabel;
    private javax.swing.JCheckBox permAplicarDescuentos;
    private javax.swing.JCheckBox permCobrarUnTicket;
    private javax.swing.JCheckBox permEliminarArtVenta;
    private javax.swing.JCheckBox permFiarProductos;
    private javax.swing.JCheckBox permRevisarHistorialV;
    private javax.swing.JCheckBox permUsarBuscadorP;
    private javax.swing.JCheckBox permUsarVarios;
    private javax.swing.JCheckBox permVentasProductosComunes;
    private javax.swing.JPanel permisosClientes;
    private javax.swing.JPanel permisosInventario;
    private javax.swing.JPanel permisosOtros;
    private javax.swing.JPanel permisosProductos;
    private javax.swing.JTabbedPane permisosTabbed;
    private javax.swing.JPanel permisosVentas;
    private javax.swing.JLabel seleccionarCajeroLabel;
    private javax.swing.JTextField usuarioBuscado;
    private javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables
}
