/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;

import javax.swing.ImageIcon;

/**
 *
 * @author luiis
 */
public class configuracion extends javax.swing.JFrame {
    private preLobby ventanaPreLobby;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(configuracion.class.getName());
    
    /**
     * Creates new form configuracion
     */
    public configuracion(preLobby ventanaPreLobby) {
         this.ventanaPreLobby = ventanaPreLobby;
         initComponents();
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBase = new javax.swing.JPanel();
        configLabel = new javax.swing.JLabel();
        generalSelect = new javax.swing.JLabel();
        admUsuariosButton = new javax.swing.JButton();
        modificarUsuarios = new javax.swing.JButton();
        personalizacionSelect = new javax.swing.JLabel();
        generadorTicketsButton = new javax.swing.JButton();
        notificacionesButton = new javax.swing.JButton();
        accesoButton = new javax.swing.JButton();
        cambiarRutaJSON = new javax.swing.JButton();
        baseDeDatosSelect = new javax.swing.JLabel();
        copiaSeguridadButton = new javax.swing.JButton();
        actualizacionesButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgBase.setBackground(new java.awt.Color(255, 255, 255));
        bgBase.setMaximumSize(new java.awt.Dimension(600, 500));
        bgBase.setMinimumSize(new java.awt.Dimension(600, 500));
        bgBase.setName(""); // NOI18N
        bgBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configLabel.setBackground(new java.awt.Color(0, 205, 203));
        configLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        configLabel.setForeground(new java.awt.Color(255, 255, 255));
        configLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configLabel.setText("Configuración");
        configLabel.setOpaque(true);
        bgBase.add(configLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 40));

        generalSelect.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        generalSelect.setForeground(new java.awt.Color(102, 102, 102));
        generalSelect.setText("General");
        bgBase.add(generalSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        admUsuariosButton.setBackground(new java.awt.Color(65, 220, 127));
        admUsuariosButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        admUsuariosButton.setForeground(new java.awt.Color(255, 255, 255));
        admUsuariosButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceAggUser.png")));
        admUsuariosButton.setText("Administrar Usuarios");
        admUsuariosButton.setBorder(null);
        admUsuariosButton.setBorderPainted(false);
        admUsuariosButton.setFocusPainted(false);
        admUsuariosButton.setFocusable(false);
        admUsuariosButton.setPreferredSize(new java.awt.Dimension(142, 27));
        admUsuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admUsuariosButtonActionPerformed(evt);
            }
        });
        bgBase.add(admUsuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 40));

        modificarUsuarios.setBackground(new java.awt.Color(65, 220, 127));
        modificarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        modificarUsuarios.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceModificarUser.png")));
        modificarUsuarios.setText("Modificar Usuarios");
        modificarUsuarios.setBorder(null);
        modificarUsuarios.setBorderPainted(false);
        modificarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarUsuarios.setFocusPainted(false);
        modificarUsuarios.setFocusable(false);
        modificarUsuarios.setMaximumSize(new java.awt.Dimension(142, 27));
        modificarUsuarios.setMinimumSize(new java.awt.Dimension(142, 27));
        modificarUsuarios.setPreferredSize(new java.awt.Dimension(142, 27));
        modificarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuariosActionPerformed(evt);
            }
        });
        bgBase.add(modificarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 40));

        personalizacionSelect.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        personalizacionSelect.setForeground(new java.awt.Color(102, 102, 102));
        personalizacionSelect.setText("Personalización ");
        bgBase.add(personalizacionSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        generadorTicketsButton.setBackground(new java.awt.Color(65, 220, 127));
        generadorTicketsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generadorTicketsButton.setForeground(new java.awt.Color(255, 255, 255));
        generadorTicketsButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceTicket.png")));
        generadorTicketsButton.setText("Generador de tickets");
        generadorTicketsButton.setBorder(null);
        generadorTicketsButton.setBorderPainted(false);
        generadorTicketsButton.setFocusPainted(false);
        generadorTicketsButton.setFocusable(false);
        generadorTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generadorTicketsButtonActionPerformed(evt);
            }
        });
        bgBase.add(generadorTicketsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 40));

        notificacionesButton.setBackground(new java.awt.Color(65, 220, 127));
        notificacionesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notificacionesButton.setForeground(new java.awt.Color(255, 255, 255));
        notificacionesButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceNotificacion.png")));
        notificacionesButton.setText("Notificaciones");
        notificacionesButton.setBorder(null);
        notificacionesButton.setBorderPainted(false);
        notificacionesButton.setFocusPainted(false);
        notificacionesButton.setFocusable(false);
        notificacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacionesButtonActionPerformed(evt);
            }
        });
        bgBase.add(notificacionesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, 40));

        accesoButton.setBackground(new java.awt.Color(65, 220, 127));
        accesoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accesoButton.setForeground(new java.awt.Color(255, 255, 255));
        accesoButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceNotificacion.png")));
        accesoButton.setText("Acceso");
        accesoButton.setBorder(null);
        accesoButton.setBorderPainted(false);
        accesoButton.setFocusPainted(false);
        accesoButton.setFocusable(false);
        accesoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoButtonActionPerformed(evt);
            }
        });
        bgBase.add(accesoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 110, 40));

        cambiarRutaJSON.setBackground(new java.awt.Color(65, 220, 127));
        cambiarRutaJSON.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cambiarRutaJSON.setForeground(new java.awt.Color(255, 255, 255));
        cambiarRutaJSON.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceTicket.png")));
        cambiarRutaJSON.setText("Ruta JSON");
        cambiarRutaJSON.setBorder(null);
        cambiarRutaJSON.setBorderPainted(false);
        cambiarRutaJSON.setFocusPainted(false);
        cambiarRutaJSON.setFocusable(false);
        cambiarRutaJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRutaJSONActionPerformed(evt);
            }
        });
        bgBase.add(cambiarRutaJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 40));

        baseDeDatosSelect.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        baseDeDatosSelect.setForeground(new java.awt.Color(102, 102, 102));
        baseDeDatosSelect.setText("Base de Datos");
        bgBase.add(baseDeDatosSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        copiaSeguridadButton.setBackground(new java.awt.Color(65, 220, 127));
        copiaSeguridadButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        copiaSeguridadButton.setForeground(new java.awt.Color(255, 255, 255));
        copiaSeguridadButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceCopiaS.png")));
        copiaSeguridadButton.setText("Copias de Seguridad");
        copiaSeguridadButton.setBorder(null);
        copiaSeguridadButton.setBorderPainted(false);
        copiaSeguridadButton.setFocusPainted(false);
        copiaSeguridadButton.setFocusable(false);
        copiaSeguridadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiaSeguridadButtonActionPerformed(evt);
            }
        });
        bgBase.add(copiaSeguridadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, 40));

        actualizacionesButton.setBackground(new java.awt.Color(65, 220, 127));
        actualizacionesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actualizacionesButton.setForeground(new java.awt.Color(255, 255, 255));
        actualizacionesButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourcePermisosUser.png")));
        actualizacionesButton.setText("Actualizaciones");
        actualizacionesButton.setBorder(null);
        actualizacionesButton.setBorderPainted(false);
        actualizacionesButton.setFocusPainted(false);
        actualizacionesButton.setFocusable(false);
        actualizacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizacionesButtonActionPerformed(evt);
            }
        });
        bgBase.add(actualizacionesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 140, 40));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bgBase.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 560, 340));

        getContentPane().add(bgBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accesoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoButtonActionPerformed

    private void notificacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacionesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificacionesButtonActionPerformed

    private void admUsuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admUsuariosButtonActionPerformed
        admUsuarios ventanaUsuarios = new admUsuarios(ventanaPreLobby);
        ventanaUsuarios.setVisible(true);
    }//GEN-LAST:event_admUsuariosButtonActionPerformed

    private void modificarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuariosActionPerformed
        modUsuarios mod = new modUsuarios();
        mod.setVisible(true);
    }//GEN-LAST:event_modificarUsuariosActionPerformed

    private void generadorTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generadorTicketsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generadorTicketsButtonActionPerformed

    private void copiaSeguridadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiaSeguridadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiaSeguridadButtonActionPerformed

    private void actualizacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizacionesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizacionesButtonActionPerformed

    private void cambiarRutaJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRutaJSONActionPerformed
        rutaJSON ruta = new rutaJSON();
        ruta.setVisible(true);
    }//GEN-LAST:event_cambiarRutaJSONActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesoButton;
    private javax.swing.JButton actualizacionesButton;
    private javax.swing.JButton admUsuariosButton;
    private javax.swing.JLabel baseDeDatosSelect;
    private javax.swing.JPanel bgBase;
    private javax.swing.JButton cambiarRutaJSON;
    private javax.swing.JLabel configLabel;
    private javax.swing.JButton copiaSeguridadButton;
    private javax.swing.JButton generadorTicketsButton;
    private javax.swing.JLabel generalSelect;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificarUsuarios;
    private javax.swing.JButton notificacionesButton;
    private javax.swing.JLabel personalizacionSelect;
    // End of variables declaration//GEN-END:variables
}
