/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import mscluna.com.app.mvc.controller.OperacionesBD;
import mscluna.com.app.mvc.controller.Sesion;
import mscluna.com.app.mvc.model.ProductoGranel;

/**
 *
 * @author luiis
 */
//CLASE JFRAME PARA ELIMINAR PRODUCTOS GRANEL, FRUTAS Y VERDURAS.
public class editarProductoGFV extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarProductoGFV.class.getName());
    private OperacionesBD operacionesBD;
    private ButtonGroup grupoUnidad;
    private float ultimoPrecioPorUnidad = 0f;
    private float ultimoPrecioPorKg = 0f;
    /**
     * Creates new form editarProductoGFV
     */
    public editarProductoGFV() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        operacionesBD = new OperacionesBD(
            Sesion.getUsuario(),
            Sesion.getContrasena(),
            Sesion.getBaseDatos()
        );
        // Agrupar los radio buttons
        grupoUnidad = new ButtonGroup();
        grupoUnidad.add(pUnidad);
        grupoUnidad.add(pKg);
        pUnidad.addActionListener(e -> precioUnitModGFV.setText(String.valueOf(ultimoPrecioPorUnidad)));
        pKg.addActionListener(e -> precioUnitModGFV.setText(String.valueOf(ultimoPrecioPorKg)));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modificacionLabelGFV = new javax.swing.JLabel();
        codProductoEditLabelGFV = new javax.swing.JLabel();
        codProdEditarGFV = new javax.swing.JFormattedTextField();
        ingresoProductoGFV = new javax.swing.JButton();
        instruccionLabelGFV = new javax.swing.JLabel();
        productoSeleccionadoGFV = new javax.swing.JLabel();
        categoriaModGFV = new javax.swing.JTextField();
        precioUnitModGFV = new javax.swing.JFormattedTextField();
        cantidadpKgModGFV = new javax.swing.JFormattedTextField();
        cantidadMinimapKgModGFV = new javax.swing.JFormattedTextField();
        aceptarModificacionGFV = new javax.swing.JButton();
        descripcionProductoIngresarGFV = new javax.swing.JLabel();
        precioUnitarioIngresarGFV = new javax.swing.JLabel();
        existenciasIngresarGFV = new javax.swing.JLabel();
        categoriaIngresarGFV = new javax.swing.JLabel();
        minimoPorKgGFV = new javax.swing.JLabel();
        descModGFV1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precioCostoMod = new javax.swing.JFormattedTextField();
        precioMayoreoMod = new javax.swing.JFormattedTextField();
        pUnidad = new javax.swing.JRadioButton();
        pKg = new javax.swing.JRadioButton();
        seleccionaUnidadLabel = new javax.swing.JLabel();
        jSeparator2GFV = new javax.swing.JSeparator();
        jSeparator1GFV = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificacionLabelGFV.setBackground(new java.awt.Color(0, 205, 203));
        modificacionLabelGFV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificacionLabelGFV.setForeground(new java.awt.Color(255, 255, 255));
        modificacionLabelGFV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificacionLabelGFV.setText("Modificar/Editar Producto");
        modificacionLabelGFV.setOpaque(true);
        jPanel1.add(modificacionLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 770, 40));

        codProductoEditLabelGFV.setForeground(new java.awt.Color(0, 0, 0));
        codProductoEditLabelGFV.setText("Ingresa el codigo del producto a editar:");
        jPanel1.add(codProductoEditLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, -1, -1));

        codProdEditarGFV.setBackground(new java.awt.Color(255, 255, 255));
        codProdEditarGFV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codProdEditarGFV.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(codProdEditarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 340, 40));

        ingresoProductoGFV.setBackground(new java.awt.Color(65, 220, 127));
        ingresoProductoGFV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ingresoProductoGFV.setForeground(new java.awt.Color(255, 255, 255));
        ingresoProductoGFV.setText("Enviar");
        ingresoProductoGFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoProductoGFVActionPerformed(evt);
            }
        });
        jPanel1.add(ingresoProductoGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 40));

        instruccionLabelGFV.setForeground(new java.awt.Color(0, 0, 0));
        instruccionLabelGFV.setText("Producto a modificar:");
        jPanel1.add(instruccionLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        productoSeleccionadoGFV.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(productoSeleccionadoGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 310, 20));

        categoriaModGFV.setBackground(new java.awt.Color(255, 255, 255));
        categoriaModGFV.setForeground(new java.awt.Color(0, 0, 0));
        categoriaModGFV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(categoriaModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 450, 40));

        precioUnitModGFV.setBackground(new java.awt.Color(255, 255, 255));
        precioUnitModGFV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        precioUnitModGFV.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(precioUnitModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 450, 40));

        cantidadpKgModGFV.setBackground(new java.awt.Color(255, 255, 255));
        cantidadpKgModGFV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cantidadpKgModGFV.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cantidadpKgModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 450, 40));

        cantidadMinimapKgModGFV.setBackground(new java.awt.Color(255, 255, 255));
        cantidadMinimapKgModGFV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cantidadMinimapKgModGFV.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cantidadMinimapKgModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 450, 40));

        aceptarModificacionGFV.setBackground(new java.awt.Color(65, 220, 127));
        aceptarModificacionGFV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aceptarModificacionGFV.setForeground(new java.awt.Color(255, 255, 255));
        aceptarModificacionGFV.setText("Modificar");
        aceptarModificacionGFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarModificacionGFVActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarModificacionGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 100, 50));

        descripcionProductoIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        descripcionProductoIngresarGFV.setText("Descripción del producto:");
        jPanel1.add(descripcionProductoIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 40));

        precioUnitarioIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        precioUnitarioIngresarGFV.setText("Precio Venta:");
        jPanel1.add(precioUnitarioIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, 40));

        existenciasIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        existenciasIngresarGFV.setText("Existencias (Cantidad p/kg):");
        jPanel1.add(existenciasIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 40));

        categoriaIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        categoriaIngresarGFV.setText("Categoria:");
        jPanel1.add(categoriaIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 70, 40));

        minimoPorKgGFV.setForeground(new java.awt.Color(0, 0, 0));
        minimoPorKgGFV.setText("Cantidad minima de producto p/Kg:");
        jPanel1.add(minimoPorKgGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 40));

        descModGFV1.setBackground(new java.awt.Color(255, 255, 255));
        descModGFV1.setForeground(new java.awt.Color(0, 0, 0));
        descModGFV1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(descModGFV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 450, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Precio Costo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Precio Mayoreo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        precioCostoMod.setBackground(new java.awt.Color(255, 255, 255));
        precioCostoMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(precioCostoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 450, 40));

        precioMayoreoMod.setBackground(new java.awt.Color(255, 255, 255));
        precioMayoreoMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(precioMayoreoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 450, 40));

        pUnidad.setForeground(new java.awt.Color(0, 0, 0));
        pUnidad.setText("Por Unidad");
        jPanel1.add(pUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        pKg.setForeground(new java.awt.Color(0, 0, 0));
        pKg.setText("Por Kg");
        jPanel1.add(pKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        seleccionaUnidadLabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionaUnidadLabel.setText("Selecciona la el tipo:");
        jPanel1.add(seleccionaUnidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        jSeparator2GFV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2GFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 810, 110));

        jSeparator1GFV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1GFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoProductoGFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoProductoGFVActionPerformed
        try {
            String id = codProdEditarGFV.getText().trim();
            ProductoGranel producto = operacionesBD.obtenerProductoGranelPorId(id);
            if (producto != null) {
                productoSeleccionadoGFV.setText(producto.getDescriptionGranel());
                descModGFV1.setText(producto.getDescriptionGranel());
                ultimoPrecioPorUnidad = producto.getPrizeForUnit();
                ultimoPrecioPorKg = producto.getPrizeForKg();
                
                // Por defecto, selecciona el tipo disponible, y muestra el precio correspondiente:
                if (ultimoPrecioPorUnidad > 0) {
                    pUnidad.setSelected(true);
                    precioUnitModGFV.setText(String.valueOf(ultimoPrecioPorUnidad));
                } else {
                    pKg.setSelected(true);
                    precioUnitModGFV.setText(String.valueOf(ultimoPrecioPorKg));
                }
                cantidadpKgModGFV.setText(String.valueOf(producto.getAmountForKg()));
                categoriaModGFV.setText(producto.getCategoryg());
                cantidadMinimapKgModGFV.setText(String.valueOf(producto.getMinimumAmount()));
                precioCostoMod.setText(String.valueOf(producto.getPrizeCost()));
                precioMayoreoMod.setText(String.valueOf(producto.getPrizeWholesale()));
            } else {
                productoSeleccionadoGFV.setText("Producto no encontrado");
                descModGFV1.setText("");
                precioUnitModGFV.setText("");
                cantidadpKgModGFV.setText("");
                categoriaModGFV.setText("");
                cantidadMinimapKgModGFV.setText("");
                precioCostoMod.setText("");
                precioMayoreoMod.setText("");

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Código inválido o error en la consulta.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ingresoProductoGFVActionPerformed

    private void aceptarModificacionGFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarModificacionGFVActionPerformed
        try {
            String id = codProdEditarGFV.getText().trim();
            String descripcion = descModGFV1.getText().trim();
            float prizeForUnit = 0f;
            float prizeForKg = 0f;
            float precio = Float.parseFloat(precioUnitModGFV.getText().trim());
            // Asignación según radiobutton seleccionado
            if (pUnidad.isSelected()) {
                prizeForUnit = precio;
                prizeForKg = 0f;
            } else if (pKg.isSelected()) {
                prizeForKg = precio;
                prizeForUnit = 0f;
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar si el precio es por unidad o por kilo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            float amountForKg = Float.parseFloat(cantidadpKgModGFV.getText().trim());
            String categoria = categoriaModGFV.getText().trim();
            float minimumAmount = Float.parseFloat(cantidadMinimapKgModGFV.getText().trim());

            // Tomar los valores de costo y mayoreo:
            float prizeCost = 0f;
            float prizeWholesale = 0f;
            try {
                prizeCost = Float.parseFloat(precioCostoMod.getText().trim());
            } catch (NumberFormatException ignored) {}
            try {
                prizeWholesale = Float.parseFloat(precioMayoreoMod.getText().trim());
            } catch (NumberFormatException ignored) {}

            ProductoGranel producto = new ProductoGranel(
                id, descripcion, prizeForKg, amountForKg, minimumAmount, prizeForUnit, categoria, prizeCost, prizeWholesale
            );

            boolean exito = operacionesBD.modificarProductoGranel(producto);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Producto granel modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar el producto granel.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor verifica los valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarModificacionGFVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new editarProductoGFV().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarModificacionGFV;
    private javax.swing.JFormattedTextField cantidadMinimapKgModGFV;
    private javax.swing.JFormattedTextField cantidadpKgModGFV;
    private javax.swing.JLabel categoriaIngresarGFV;
    private javax.swing.JTextField categoriaModGFV;
    private javax.swing.JFormattedTextField codProdEditarGFV;
    private javax.swing.JLabel codProductoEditLabelGFV;
    private javax.swing.JTextField descModGFV1;
    private javax.swing.JLabel descripcionProductoIngresarGFV;
    private javax.swing.JLabel existenciasIngresarGFV;
    private javax.swing.JButton ingresoProductoGFV;
    private javax.swing.JLabel instruccionLabelGFV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1GFV;
    private javax.swing.JSeparator jSeparator2GFV;
    private javax.swing.JLabel minimoPorKgGFV;
    private javax.swing.JLabel modificacionLabelGFV;
    private javax.swing.JRadioButton pKg;
    private javax.swing.JRadioButton pUnidad;
    private javax.swing.JFormattedTextField precioCostoMod;
    private javax.swing.JFormattedTextField precioMayoreoMod;
    private javax.swing.JFormattedTextField precioUnitModGFV;
    private javax.swing.JLabel precioUnitarioIngresarGFV;
    private javax.swing.JLabel productoSeleccionadoGFV;
    private javax.swing.JLabel seleccionaUnidadLabel;
    // End of variables declaration//GEN-END:variables
}
