/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;
import javax.swing.JOptionPane;
import mscluna.com.app.mvc.controller.OperacionesBD;
import mscluna.com.app.mvc.controller.Sesion;
import mscluna.com.app.mvc.model.Producto;

/**
 *
 * @author luiis
 */
public class editarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarProducto.class.getName());
    private OperacionesBD operacionesBD;
    /**
     * Creates new form editarProduct
     */
    public editarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         operacionesBD = new OperacionesBD(
                Sesion.getUsuario(),
                Sesion.getContrasena(),
                Sesion.getBaseDatos()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codProductoEditLabel = new javax.swing.JLabel();
        codProdEditar = new javax.swing.JFormattedTextField();
        ingresoProductoMod = new javax.swing.JButton();
        modificacionLabel = new javax.swing.JLabel();
        instruccionLabel = new javax.swing.JLabel();
        productoSeleccionado = new javax.swing.JLabel();
        modificarDescLabel = new javax.swing.JLabel();
        descMod = new javax.swing.JTextField();
        modificarPrecioULabel = new javax.swing.JLabel();
        precioUnitMod = new javax.swing.JFormattedTextField();
        modificarCantidadLabel = new javax.swing.JLabel();
        cantidadMod = new javax.swing.JFormattedTextField();
        modificarCategoriaLabel = new javax.swing.JLabel();
        categoriaMod = new javax.swing.JTextField();
        modificarPrecioDescuentoLabel = new javax.swing.JLabel();
        precioDescuentoMod = new javax.swing.JFormattedTextField();
        modificarImporteLabel = new javax.swing.JLabel();
        importeMod = new javax.swing.JFormattedTextField();
        asd = new javax.swing.JLabel();
        minimumMod = new javax.swing.JFormattedTextField();
        aceptarModificacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codProductoEditLabel.setForeground(new java.awt.Color(0, 0, 0));
        codProductoEditLabel.setText("Ingresa el codigo del producto a editar:");
        jPanel1.add(codProductoEditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, -1, -1));

        codProdEditar.setBackground(new java.awt.Color(255, 255, 255));
        codProdEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codProdEditar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(codProdEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 340, 40));

        ingresoProductoMod.setBackground(new java.awt.Color(65, 220, 127));
        ingresoProductoMod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ingresoProductoMod.setForeground(new java.awt.Color(255, 255, 255));
        ingresoProductoMod.setText("Enviar");
        ingresoProductoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoProductoModActionPerformed(evt);
            }
        });
        jPanel1.add(ingresoProductoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 40));

        modificacionLabel.setBackground(new java.awt.Color(0, 205, 203));
        modificacionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificacionLabel.setForeground(new java.awt.Color(255, 255, 255));
        modificacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificacionLabel.setText("Modificar/Editar Producto");
        modificacionLabel.setOpaque(true);
        jPanel1.add(modificacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 770, 40));

        instruccionLabel.setForeground(new java.awt.Color(0, 0, 0));
        instruccionLabel.setText("Producto a modificar:");
        jPanel1.add(instruccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        productoSeleccionado.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(productoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 310, 20));

        modificarDescLabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarDescLabel.setText("Modificar descripcion:");
        jPanel1.add(modificarDescLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 30));

        descMod.setBackground(new java.awt.Color(255, 255, 255));
        descMod.setForeground(new java.awt.Color(0, 0, 0));
        descMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(descMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 450, 40));

        modificarPrecioULabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarPrecioULabel.setText("Modificar precio unitario:");
        jPanel1.add(modificarPrecioULabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 140, 40));

        precioUnitMod.setBackground(new java.awt.Color(255, 255, 255));
        precioUnitMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        precioUnitMod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(precioUnitMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 450, 40));

        modificarCantidadLabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarCantidadLabel.setText("Modificar existencia (cantidad):");
        jPanel1.add(modificarCantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 30));

        cantidadMod.setBackground(new java.awt.Color(255, 255, 255));
        cantidadMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cantidadMod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cantidadMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 450, 40));

        modificarCategoriaLabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarCategoriaLabel.setText("Modificar categoria:");
        jPanel1.add(modificarCategoriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, 30));

        categoriaMod.setBackground(new java.awt.Color(255, 255, 255));
        categoriaMod.setForeground(new java.awt.Color(0, 0, 0));
        categoriaMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(categoriaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 450, 40));

        modificarPrecioDescuentoLabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarPrecioDescuentoLabel.setText("Modificar precio unitario (Sabados):");
        jPanel1.add(modificarPrecioDescuentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 200, 40));

        precioDescuentoMod.setBackground(new java.awt.Color(255, 255, 255));
        precioDescuentoMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        precioDescuentoMod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(precioDescuentoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 450, 40));

        modificarImporteLabel.setForeground(new java.awt.Color(0, 0, 0));
        modificarImporteLabel.setText("Modificar importe:");
        jPanel1.add(modificarImporteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, 40));

        importeMod.setBackground(new java.awt.Color(255, 255, 255));
        importeMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        importeMod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(importeMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 450, 40));

        asd.setForeground(new java.awt.Color(0, 0, 0));
        asd.setText("Modificar minimo: ");
        jPanel1.add(asd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 516, 110, 30));

        minimumMod.setBackground(new java.awt.Color(255, 255, 255));
        minimumMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        minimumMod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(minimumMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 450, 40));

        aceptarModificacion.setBackground(new java.awt.Color(65, 220, 127));
        aceptarModificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aceptarModificacion.setForeground(new java.awt.Color(255, 255, 255));
        aceptarModificacion.setText("Modificar");
        aceptarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarModificacionActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 100, 50));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 810, 110));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarModificacionActionPerformed
        try {
            String id = codProdEditar.getText().trim();
            String descripcion = descMod.getText().trim();
            float unitPrice = Float.parseFloat(precioUnitMod.getText().trim());
            int amount = Integer.parseInt(cantidadMod.getText().trim());
            String categoria = categoriaMod.getText().trim();
            String descuento = precioDescuentoMod.getText().trim();
            float importe = Float.parseFloat(importeMod.getText().trim());
            int minimum = Integer.parseInt(minimumMod.getText().trim());

            Producto producto = new Producto(id, descripcion, unitPrice, amount, categoria, descuento, importe, minimum);

            boolean exito = operacionesBD.modificarProducto(producto);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor verifica los valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarModificacionActionPerformed

    private void ingresoProductoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoProductoModActionPerformed
            try {
                String id = codProdEditar.getText().trim();
                Producto producto = operacionesBD.obtenerProductoPorId(id);
                if (producto != null) {
                    productoSeleccionado.setText(producto.getDescription());
                    descMod.setText(producto.getDescription());
                    precioUnitMod.setText(String.valueOf(producto.getUnitPrice()));
                    cantidadMod.setText(String.valueOf(producto.getAmount()));
                    categoriaMod.setText(producto.getCategory());
                    precioDescuentoMod.setText(producto.getDiscount());
                    importeMod.setText(String.valueOf(producto.getImporte()));
                    minimumMod.setText(String.valueOf(producto.getMinimum()));
                } else {
                    productoSeleccionado.setText("Producto no encontrado");
                    // Limpiar campos
                    descMod.setText("");
                    precioUnitMod.setText("");
                    cantidadMod.setText("");
                    categoriaMod.setText("");
                    precioDescuentoMod.setText("");
                    importeMod.setText("");
                    minimumMod.setText("");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Código inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_ingresoProductoModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new editarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarModificacion;
    private javax.swing.JLabel asd;
    private javax.swing.JFormattedTextField cantidadMod;
    private javax.swing.JTextField categoriaMod;
    private javax.swing.JFormattedTextField codProdEditar;
    private javax.swing.JLabel codProductoEditLabel;
    private javax.swing.JTextField descMod;
    private javax.swing.JFormattedTextField importeMod;
    private javax.swing.JButton ingresoProductoMod;
    private javax.swing.JLabel instruccionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField minimumMod;
    private javax.swing.JLabel modificacionLabel;
    private javax.swing.JLabel modificarCantidadLabel;
    private javax.swing.JLabel modificarCategoriaLabel;
    private javax.swing.JLabel modificarDescLabel;
    private javax.swing.JLabel modificarImporteLabel;
    private javax.swing.JLabel modificarPrecioDescuentoLabel;
    private javax.swing.JLabel modificarPrecioULabel;
    private javax.swing.JFormattedTextField precioDescuentoMod;
    private javax.swing.JFormattedTextField precioUnitMod;
    private javax.swing.JLabel productoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
