/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;
import javax.swing.JOptionPane;
import mscluna.com.app.mvc.controller.OperacionesBD;
import mscluna.com.app.mvc.controller.Sesion;
import mscluna.com.app.mvc.model.ProductoGranel;

/**
 *
 * @author luiis
 */
//CLASE JFRAME PARA ELIMINAR PRODUCTOS GRANEL, FRUTAS Y VERDURAS.
public class editarProductoGFV extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarProductoGFV.class.getName());
    private OperacionesBD operacionesBD;
    /**
     * Creates new form editarProductoGFV
     */
    public editarProductoGFV() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         operacionesBD = new OperacionesBD(
            Sesion.getUsuario(),
            Sesion.getContrasena(),
            Sesion.getBaseDatos()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modificacionLabelGFV = new javax.swing.JLabel();
        codProductoEditLabelGFV = new javax.swing.JLabel();
        codProdEditarGFV = new javax.swing.JFormattedTextField();
        ingresoProductoGFV = new javax.swing.JButton();
        jSeparator2GFV = new javax.swing.JSeparator();
        instruccionLabelGFV = new javax.swing.JLabel();
        productoSeleccionadoGFV = new javax.swing.JLabel();
        categoriaModGFV = new javax.swing.JTextField();
        precioUnitModGFV = new javax.swing.JFormattedTextField();
        cantidadpKgModGFV = new javax.swing.JFormattedTextField();
        precioPKgGFV = new javax.swing.JTextField();
        cantidadMinimapKgModGFV = new javax.swing.JFormattedTextField();
        aceptarModificacionGFV = new javax.swing.JButton();
        descripcionProductoIngresarGFV = new javax.swing.JLabel();
        precioUnitarioIngresarGFV = new javax.swing.JLabel();
        precioPorKgIngresarGFV = new javax.swing.JLabel();
        existenciasIngresarGFV = new javax.swing.JLabel();
        categoriaIngresarGFV = new javax.swing.JLabel();
        minimoPorKgGFV = new javax.swing.JLabel();
        jSeparator1GFV = new javax.swing.JSeparator();
        descModGFV1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificacionLabelGFV.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        modificacionLabelGFV.setForeground(new java.awt.Color(0, 0, 0));
        modificacionLabelGFV.setText("Modificar/Editar Producto");
        jPanel1.add(modificacionLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        codProductoEditLabelGFV.setForeground(new java.awt.Color(0, 0, 0));
        codProductoEditLabelGFV.setText("Ingresa el codigo del producto a editar:");
        jPanel1.add(codProductoEditLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 102, -1, -1));
        jPanel1.add(codProdEditarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 340, 40));

        ingresoProductoGFV.setText("Enviar");
        ingresoProductoGFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoProductoGFVActionPerformed(evt);
            }
        });
        jPanel1.add(ingresoProductoGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 40));

        jSeparator2GFV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator2GFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 810, 110));

        instruccionLabelGFV.setForeground(new java.awt.Color(0, 0, 0));
        instruccionLabelGFV.setText("Producto a modificar:");
        jPanel1.add(instruccionLabelGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        productoSeleccionadoGFV.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(productoSeleccionadoGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 310, 20));
        jPanel1.add(categoriaModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 450, 40));
        jPanel1.add(precioUnitModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 450, 40));
        jPanel1.add(cantidadpKgModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 450, 40));
        jPanel1.add(precioPKgGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 450, 40));
        jPanel1.add(cantidadMinimapKgModGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 450, 40));

        aceptarModificacionGFV.setText("Modificar");
        aceptarModificacionGFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarModificacionGFVActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarModificacionGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 100, 50));

        descripcionProductoIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        descripcionProductoIngresarGFV.setText("Descripción del producto:");
        jPanel1.add(descripcionProductoIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 40));

        precioUnitarioIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        precioUnitarioIngresarGFV.setText("Precio unitario:");
        jPanel1.add(precioUnitarioIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 40));

        precioPorKgIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        precioPorKgIngresarGFV.setText("Precio p/Kg:");
        jPanel1.add(precioPorKgIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, 40));

        existenciasIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        existenciasIngresarGFV.setText("Existencias (Cantidad p/kg):");
        jPanel1.add(existenciasIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, 40));

        categoriaIngresarGFV.setForeground(new java.awt.Color(0, 0, 0));
        categoriaIngresarGFV.setText("Categoria:");
        jPanel1.add(categoriaIngresarGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 80, 40));

        minimoPorKgGFV.setForeground(new java.awt.Color(0, 0, 0));
        minimoPorKgGFV.setText("Cantidad minima de producto p/Kg:");
        jPanel1.add(minimoPorKgGFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 220, 40));

        jSeparator1GFV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1GFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 810, 510));
        jPanel1.add(descModGFV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 450, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoProductoGFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoProductoGFVActionPerformed
        try {
            String id = codProdEditarGFV.getText().trim();
            ProductoGranel producto = operacionesBD.obtenerProductoGranelPorId(id);
            if (producto != null) {
                productoSeleccionadoGFV.setText(producto.getDescriptionGranel());
                descModGFV1.setText(producto.getDescriptionGranel());
                precioUnitModGFV.setText(String.valueOf(producto.getPrizeForUnit()));
                precioPKgGFV.setText(String.valueOf(producto.getPrizeForKg()));
                cantidadpKgModGFV.setText(String.valueOf(producto.getAmountForKg()));
                categoriaModGFV.setText(producto.getCategoryg());
                cantidadMinimapKgModGFV.setText(String.valueOf(producto.getMinimumAmount()));
            } else {
                productoSeleccionadoGFV.setText("Producto no encontrado");
                descModGFV1.setText("");
                precioUnitModGFV.setText("");
                precioPKgGFV.setText("");
                cantidadpKgModGFV.setText("");
                categoriaModGFV.setText("");
                cantidadMinimapKgModGFV.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Código inválido o error en la consulta.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ingresoProductoGFVActionPerformed

    private void aceptarModificacionGFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarModificacionGFVActionPerformed
        try {
            String id = codProdEditarGFV.getText().trim();
            String descripcion = descModGFV1.getText().trim();
            float prizeForUnit = Float.parseFloat(precioUnitModGFV.getText().trim());
            float prizeForKg = Float.parseFloat(precioPKgGFV.getText().trim());
            float amountForKg = Float.parseFloat(cantidadpKgModGFV.getText().trim());
            String categoria = categoriaModGFV.getText().trim();
            float minimumAmount = Float.parseFloat(cantidadMinimapKgModGFV.getText().trim());

            ProductoGranel producto = new ProductoGranel(
                id, descripcion, prizeForKg, amountForKg, minimumAmount, prizeForUnit, categoria
            );

            boolean exito = operacionesBD.modificarProductoGranel(producto);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Producto granel modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar el producto granel.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor verifica los valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarModificacionGFVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new editarProductoGFV().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarModificacionGFV;
    private javax.swing.JFormattedTextField cantidadMinimapKgModGFV;
    private javax.swing.JFormattedTextField cantidadpKgModGFV;
    private javax.swing.JLabel categoriaIngresarGFV;
    private javax.swing.JTextField categoriaModGFV;
    private javax.swing.JFormattedTextField codProdEditarGFV;
    private javax.swing.JLabel codProductoEditLabelGFV;
    private javax.swing.JTextField descModGFV1;
    private javax.swing.JLabel descripcionProductoIngresarGFV;
    private javax.swing.JLabel existenciasIngresarGFV;
    private javax.swing.JButton ingresoProductoGFV;
    private javax.swing.JLabel instruccionLabelGFV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1GFV;
    private javax.swing.JSeparator jSeparator2GFV;
    private javax.swing.JLabel minimoPorKgGFV;
    private javax.swing.JLabel modificacionLabelGFV;
    private javax.swing.JTextField precioPKgGFV;
    private javax.swing.JLabel precioPorKgIngresarGFV;
    private javax.swing.JFormattedTextField precioUnitModGFV;
    private javax.swing.JLabel precioUnitarioIngresarGFV;
    private javax.swing.JLabel productoSeleccionadoGFV;
    // End of variables declaration//GEN-END:variables
}
