/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;
import javax.swing.JOptionPane;
import mscluna.com.app.mvc.controller.OperacionesBD;
import mscluna.com.app.mvc.controller.Sesion;
import mscluna.com.app.mvc.model.Producto;
import mscluna.com.app.mvc.model.ProductoGranel;

/**
 *
 * @author luiis
 */
public class eliminarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(eliminarProducto.class.getName());
    private OperacionesBD operacionesBD;
    /**
     * Creates new form eliminarProducto
     */
    public eliminarProducto() {
         initComponents();
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         operacionesBD = new OperacionesBD(
         Sesion.getUsuario(),
         Sesion.getContrasena(),
         Sesion.getBaseDatos()
         );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eliminacionLabel = new javax.swing.JLabel();
        advLabel = new javax.swing.JLabel();
        codProductoElimLabel = new javax.swing.JLabel();
        codProdEliminar = new javax.swing.JFormattedTextField();
        eliminarProdButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminacionLabel.setBackground(new java.awt.Color(0, 205, 203));
        eliminacionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminacionLabel.setForeground(new java.awt.Color(255, 255, 255));
        eliminacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminacionLabel.setText("Eliminar Producto");
        eliminacionLabel.setOpaque(true);
        jPanel1.add(eliminacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, 40));

        advLabel.setForeground(new java.awt.Color(102, 102, 102));
        advLabel.setText("(El producto se eliminara totalmente de la base de datos)");
        jPanel1.add(advLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 20));

        codProductoElimLabel.setForeground(new java.awt.Color(0, 0, 0));
        codProductoElimLabel.setText("Ingresa el codigo del producto a eliminar:");
        jPanel1.add(codProductoElimLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 40));
        jPanel1.add(codProdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 400, 40));

        eliminarProdButton.setBackground(new java.awt.Color(65, 220, 127));
        eliminarProdButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarProdButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarProdButton.setText("Eliminar");
        eliminarProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProdButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarProdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 100, 40));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProdButtonActionPerformed
        String codigo = codProdEliminar.getText().trim();

        // Primero intenta en products
        Producto prod = operacionesBD.obtenerProductoPorId(codigo);
        if (prod != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar el producto " + prod.getDescription() + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean exito = operacionesBD.eliminarProducto(codigo);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            return;
        }

        // Si no existe en products, intenta en g_products
        ProductoGranel prodg = operacionesBD.obtenerProductoGranelPorId(codigo);
        if (prodg != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar el producto granel " + prodg.getDescriptionGranel() + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean exito = operacionesBD.eliminarProductoGranel(codigo);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Producto granel eliminado correctamente.");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el producto granel.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            return;
        }

        JOptionPane.showMessageDialog(this, "No se encontró ningún producto con ese código.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_eliminarProdButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new eliminarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advLabel;
    private javax.swing.JFormattedTextField codProdEliminar;
    private javax.swing.JLabel codProductoElimLabel;
    private javax.swing.JLabel eliminacionLabel;
    private javax.swing.JButton eliminarProdButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
