package mscluna.com.app.mvc.view;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luiis
 */
public class login extends javax.swing.JFrame {
        private boolean eyeNew = true;

    /**
     * Creates new form jfondo
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        userfield.setMargin(new Insets(5, 10, 5, 5));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        mscMessage1 = new javax.swing.JLabel();
        mscMessage2 = new javax.swing.JLabel();
        iconUser = new javax.swing.JLabel();
        eyeButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        userfield = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        iconPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mscMessage1.setFont(new java.awt.Font("SimSun", 0, 85)); // NOI18N
        mscMessage1.setForeground(new java.awt.Color(0, 153, 153));
        mscMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mscMessage1.setText("LUNA");
        bgpanel.add(mscMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, 70));

        mscMessage2.setFont(new java.awt.Font("SimSun", 0, 40)); // NOI18N
        mscMessage2.setForeground(new java.awt.Color(0, 205, 203));
        mscMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mscMessage2.setText("MISCELANEA");
        bgpanel.add(mscMessage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 290, 70));

        iconUser.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/userIconPNG.png")));
        bgpanel.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 239, 40, 40));

        eyeButton.setVisible(false);
        eyeButton.setBackground(null);
        eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeO.png")));
        eyeButton.setBorderPainted(false);
        eyeButton.setContentAreaFilled(false);
        eyeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeButton.setFocusPainted(false);
        eyeButton.setFocusable(false);
        eyeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeButtonMouseClicked(evt);
            }
        });
        bgpanel.add(eyeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 30, 40));

        sendButton.setBackground(new java.awt.Color(0, 153, 153));
        sendButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Enviar");
        sendButton.setBorder(null);
        sendButton.setBorderPainted(false);
        sendButton.setFocusPainted(false);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        bgpanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 30));

        userfield.setEditable(false);
        userfield.setBackground(new Color(30,30,30));
        userfield.setBackground(new java.awt.Color(255, 255, 255));
        userfield.setForeground(new java.awt.Color(102, 102, 102));
        userfield.setText("Usuario");
        userfield.setToolTipText("");
        userfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        userfield.setCaretColor(new java.awt.Color(30, 30, 30));
        userfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userfieldMouseClicked(evt);
            }
        });
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        bgpanel.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 290, 40));

        passfield.setEditable(false);
        passfield.setBackground(new Color(30,30,30));
        passfield.setBackground(new java.awt.Color(255, 255, 255));
        passfield.setForeground(new java.awt.Color(102, 102, 102));
        passfield.setText("Contraseña");
        passfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        passfield.setCaretColor(new java.awt.Color(255, 255, 255));
        passfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passfieldMouseClicked(evt);
            }
        });
        bgpanel.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, 40));
        passfield.setEchoChar((char) 0);

        iconPass.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/passIconPNG.png")));
        bgpanel.add(iconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 300, 40, 36));

        getContentPane().add(bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMouseClicked
        userfield.setEditable(true);
        if (userfield.getText().equals("Usuario")){
            userfield.setText("");
            userfield.setForeground(Color.black);
            userfield.setCaretColor(Color.black);
            userfield.setText("root");
        }
    }//GEN-LAST:event_userfieldMouseClicked

    private void passfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passfieldMouseClicked
        passfield.setEditable(true);
        eyeButton.setVisible(true);
        if (String.valueOf(passfield.getPassword()).equals("Contraseña")){
            passfield.setText("");
            passfield.setEchoChar('*');
            passfield.setForeground(Color.black);
            passfield.setCaretColor(Color.black);
        }
    }//GEN-LAST:event_passfieldMouseClicked

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        passfield.setEchoChar('*');
        String usuario = userfield.getText().trim();
        String contrasena = new String(passfield.getPassword()).trim();
        String nombreBD = "nube_database_ta";

        // Elimina el placeholder antes de validar
        if (usuario.equals("Usuario")) usuario = "";
        if (contrasena.equals("Contraseña")) contrasena = "";

        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
            return;
        }

        Connection conn = mscluna.com.app.mvc.controller.ConexionBD.getConexion(usuario, contrasena, nombreBD);

        if (conn != null) {
            // Guarda los datos de sesión para uso posterior
            mscluna.com.app.mvc.controller.Sesion.iniciarSesion(usuario, contrasena, nombreBD);

            JOptionPane.showMessageDialog(this, "¡Conexión exitosa a la base de datos '" + nombreBD + "'!");

            // Ir al lobby
            preLobby goprelobby = new preLobby();
            goprelobby.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al conectar. Verifique usuario, contraseña o nombre de la base de datos.");
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    private void eyeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeButtonMouseClicked
         if (eyeNew) {
                eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeC.png")));
                passfield.setEchoChar((char)0);
        } else {
                eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeO.png")));
                passfield.setEchoChar('*');
        }
        eyeNew = !eyeNew; // Alternar estado                
    }//GEN-LAST:event_eyeButtonMouseClicked

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgpanel;
    private javax.swing.JButton eyeButton;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel mscMessage1;
    private javax.swing.JLabel mscMessage2;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
