/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mscluna.com.app.mvc.model.UsuarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import mscluna.com.app.mvc.controller.ConexionBD;

/**
 *
 * @author luiis
 */
public class preLobby extends javax.swing.JFrame {
    private boolean eyeNew = true;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(preLobby.class.getName());

    /**
     * Creates new form preLobby
     */
    public preLobby() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        inicioTurnoLabel = new javax.swing.JLabel();
        seleccionarCajeroLabel = new javax.swing.JLabel();
        seleccionarCajero = new javax.swing.JComboBox<>();
        dineroEnCajaLabel = new javax.swing.JLabel();
        dineroEnCaja = new javax.swing.JFormattedTextField();
        turnoLabel = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox<>();
        empezarTurno = new javax.swing.JButton();
        cerrarButton = new javax.swing.JButton();
        passLabel = new javax.swing.JLabel();
        contraUser = new javax.swing.JPasswordField();
        eyeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioTurnoLabel.setBackground(new java.awt.Color(0, 205, 203));
        inicioTurnoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inicioTurnoLabel.setForeground(new java.awt.Color(255, 255, 255));
        inicioTurnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioTurnoLabel.setText("Inicio de turno");
        inicioTurnoLabel.setOpaque(true);
        panelInicio.add(inicioTurnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 40));

        seleccionarCajeroLabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCajeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionarCajeroLabel.setText("Cajero:");
        panelInicio.add(seleccionarCajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, 30));

        seleccionarCajero.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarCajero.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cajero1" }));
        panelInicio.add(seleccionarCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, 30));

        dineroEnCajaLabel.setForeground(new java.awt.Color(0, 0, 0));
        dineroEnCajaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dineroEnCajaLabel.setText("Dinero en caja:");
        panelInicio.add(dineroEnCajaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, 30));

        dineroEnCaja.setBackground(new java.awt.Color(255, 255, 255));
        dineroEnCaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dineroEnCaja.setForeground(new java.awt.Color(0, 0, 0));
        dineroEnCaja.setText("800");
        panelInicio.add(dineroEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 160, 30));

        turnoLabel.setForeground(new java.awt.Color(0, 0, 0));
        turnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnoLabel.setText("Turno:");
        panelInicio.add(turnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, 30));

        turno.setBackground(new java.awt.Color(255, 255, 255));
        turno.setForeground(new java.awt.Color(0, 0, 0));
        turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino" }));
        panelInicio.add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 160, 30));

        empezarTurno.setBackground(new java.awt.Color(0, 153, 153));
        empezarTurno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empezarTurno.setForeground(new java.awt.Color(255, 255, 255));
        empezarTurno.setText("Empezar Turno");
        empezarTurno.setBorder(null);
        empezarTurno.setFocusPainted(false);
        empezarTurno.setFocusable(false);
        empezarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarTurnoActionPerformed(evt);
            }
        });
        panelInicio.add(empezarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 30));

        cerrarButton.setBackground(new java.awt.Color(0, 153, 153));
        cerrarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cerrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cerrarButton.setText("Cerrar");
        cerrarButton.setBorder(null);
        cerrarButton.setFocusPainted(false);
        cerrarButton.setFocusable(false);
        cerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarButtonActionPerformed(evt);
            }
        });
        panelInicio.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 110, 30));

        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLabel.setText("Contraseña:");
        panelInicio.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 30));

        contraUser.setBackground(new java.awt.Color(255, 255, 255));
        contraUser.setForeground(new java.awt.Color(0, 0, 0));
        contraUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelInicio.add(contraUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 160, 30));

        eyeButton.setVisible(false);
        eyeButton.setBackground(null);
        eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeO.png")));
        eyeButton.setBorderPainted(false);
        eyeButton.setContentAreaFilled(false);
        eyeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeButton.setFocusPainted(false);
        eyeButton.setFocusable(false);
        eyeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeButtonMouseClicked(evt);
            }
        });
        panelInicio.add(eyeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 30, 30));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelInicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 510, 270));

        getContentPane().add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void actualizarCajeros() {
    try {
        Connection conn = mscluna.com.app.mvc.controller.ConexionBD.getConexion("admin", "adminpassword", "nube_database_ta");
        String sql = "SELECT username FROM usuarios";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery();

        // Ahora seleccionaCajero es de instancia
        seleccionarCajero.removeAllItems();
        while (rs.next()) {
            seleccionarCajero.addItem(rs.getString("username"));
        }

        conn.close();
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error actualizando cajeros: " + ex.getMessage());
        ex.printStackTrace();
    }
}
    private void empezarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarTurnoActionPerformed
        String usuario = seleccionarCajero.getSelectedItem().toString();
        String contrasena = new String(contraUser.getPassword()).trim();

        Connection conn = ConexionBD.getConexion(usuario, contrasena, "nube_database_ta");
        if (conn != null) {
            // Acceso concedido: abrir lobby
            lobby ventanaLobby = new lobby(usuario,getTurno(), getDineroC());
            ventanaLobby.setVisible(true);
            this.dispose();
            try { conn.close(); } catch (SQLException e) { }
        } else {
            // Acceso denegado
            JOptionPane.showMessageDialog(this, "Usuario o contraseña de base de datos incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_empezarTurnoActionPerformed

    private void cerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cerrarButtonActionPerformed

    private void eyeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeButtonMouseClicked
        if (eyeNew) {
            eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeC.png")));
            contraUser.setEchoChar((char)0);
        } else {
            eyeButton.setIcon(new ImageIcon(getClass().getResource("/mscluna/com/app/mvc/images/resourceEyeO.png")));
            contraUser.setEchoChar('*');
        }
        eyeNew = !eyeNew; // Alternar estado
    }//GEN-LAST:event_eyeButtonMouseClicked
    
    public String getCajeroSeleccionado() {
        return seleccionarCajero.getSelectedItem().toString();
    }
    public String getTurno(){
        return turno.getSelectedItem().toString();
    }
    public String getDineroC(){
        return dineroEnCaja.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new preLobby().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarButton;
    private javax.swing.JPasswordField contraUser;
    private javax.swing.JFormattedTextField dineroEnCaja;
    private javax.swing.JLabel dineroEnCajaLabel;
    private javax.swing.JButton empezarTurno;
    private javax.swing.JButton eyeButton;
    private javax.swing.JLabel inicioTurnoLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JLabel passLabel;
    private javax.swing.JComboBox<String> seleccionarCajero;
    private javax.swing.JLabel seleccionarCajeroLabel;
    private javax.swing.JComboBox<String> turno;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
