/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;

/**
 *
 * @author luiis
 */
public class preLobby extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(preLobby.class.getName());

    /**
     * Creates new form preLobby
     */
    public preLobby() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inicioTurnoLabel = new javax.swing.JLabel();
        seleccionarCajeroLabel = new javax.swing.JLabel();
        cajeroAtendiendo = new javax.swing.JComboBox<>();
        dineroEnCajaLabel = new javax.swing.JLabel();
        dineroEnCaja = new javax.swing.JFormattedTextField();
        turnoLabel = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox<>();
        empezarTurno = new javax.swing.JButton();
        cerrarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioTurnoLabel.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        inicioTurnoLabel.setForeground(new java.awt.Color(0, 0, 0));
        inicioTurnoLabel.setText("Inicio de turno");
        jPanel1.add(inicioTurnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        seleccionarCajeroLabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCajeroLabel.setText("Cajero:");
        jPanel1.add(seleccionarCajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 30));

        cajeroAtendiendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROOT" }));
        jPanel1.add(cajeroAtendiendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 30));

        dineroEnCajaLabel.setForeground(new java.awt.Color(0, 0, 0));
        dineroEnCajaLabel.setText("Dinero en caja:");
        jPanel1.add(dineroEnCajaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 249, 100, 20));

        dineroEnCaja.setText("800");
        jPanel1.add(dineroEnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 244, 150, 30));

        turnoLabel.setForeground(new java.awt.Color(0, 0, 0));
        turnoLabel.setText("Turno:");
        jPanel1.add(turnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 70, 30));

        turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde" }));
        jPanel1.add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 30));

        empezarTurno.setText("Empezar Turno");
        empezarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarTurnoActionPerformed(evt);
            }
        });
        jPanel1.add(empezarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        cerrarButton.setText("Cerrar");
        cerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 110, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 500, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarTurnoActionPerformed
    lobby golobby = new lobby(getCajeroSeleccionado(), getTurno(), getDineroC());
    golobby.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_empezarTurnoActionPerformed

    private void cerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cerrarButtonActionPerformed
    public String getCajeroSeleccionado() {
        return cajeroAtendiendo.getSelectedItem().toString();
    }
    public String getTurno(){
        return turno.getSelectedItem().toString();
    }
    public String getDineroC(){
        return dineroEnCaja.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new preLobby().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cajeroAtendiendo;
    private javax.swing.JButton cerrarButton;
    private javax.swing.JFormattedTextField dineroEnCaja;
    private javax.swing.JLabel dineroEnCajaLabel;
    private javax.swing.JButton empezarTurno;
    private javax.swing.JLabel inicioTurnoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel seleccionarCajeroLabel;
    private javax.swing.JComboBox<String> turno;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
