/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mscluna.com.app.mvc.view;

import javax.swing.JOptionPane;
import mscluna.com.app.mvc.controller.ConexionBD;
import mscluna.com.app.mvc.controller.Sesion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author luiis
 */
public class rutaJSON extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(rutaJSON.class.getName());

    /**
     * Creates new form rutaJSON
     */
    public rutaJSON() {
            initComponents();
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rutaJsonLabel = new javax.swing.JLabel();
        instruccion = new javax.swing.JLabel();
        rutaJson = new javax.swing.JTextField();
        enviarRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        rutaJsonLabel.setBackground(new java.awt.Color(0, 205, 203));
        rutaJsonLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rutaJsonLabel.setForeground(new java.awt.Color(255, 255, 255));
        rutaJsonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rutaJsonLabel.setText("Editar Ruta JSON");
        rutaJsonLabel.setOpaque(true);

        instruccion.setForeground(new java.awt.Color(0, 0, 0));
        instruccion.setText("Ingresa la ruta donde se guardaran los archivos .JSON");

        rutaJson.setBackground(new java.awt.Color(255, 255, 255));
        rutaJson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        enviarRuta.setBackground(new java.awt.Color(65, 220, 127));
        enviarRuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enviarRuta.setForeground(new java.awt.Color(255, 255, 255));
        enviarRuta.setText("Enviar");
        enviarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rutaJsonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(rutaJson, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(enviarRuta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(instruccion)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rutaJsonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(instruccion)
                .addGap(18, 18, 18)
                .addComponent(rutaJson, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enviarRuta)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarRutaActionPerformed
        String ruta = rutaJson.getText().trim();

        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una ruta.");
            return;
        }

        java.io.File carpeta = new java.io.File(ruta);
        if (!carpeta.exists() || !carpeta.isDirectory()) {
            JOptionPane.showMessageDialog(this, "La ruta no es una carpeta válida.");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de guardar esta ruta?",
                "Confirmar ruta",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try (Connection conn = ConexionBD.getConexion(
                    Sesion.getUsuario(),
                    Sesion.getContrasena(),
                    Sesion.getBaseDatos())) {

                String sql = "INSERT INTO rutas_json (ruta) VALUES (?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, ruta);

                int filas = ps.executeUpdate();
                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "Ruta guardada correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar la ruta.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_enviarRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new rutaJSON().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarRuta;
    private javax.swing.JLabel instruccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rutaJson;
    private javax.swing.JLabel rutaJsonLabel;
    // End of variables declaration//GEN-END:variables
}
